### ISSUE TITLE
API calls retry

### ISSUE THREAD

**Issue by spa-87** [SungardAS/spotinst-lambda#4]
Hi, during use of current tool I've noticed here isn't implemented retry for SpotInst API calls.

The use case:
I run stack update and get failed update. At lambda function logs I can see the error:

```
{
    "errorMessage": "elasticgroup update failed: 504"
}
```

Couple seconds later I ran stack update one more time and it was successful.
I can see there isn't configured retry for `requests` call:
https://github.com/SungardAS/spotinst-lambda/blob/master/lib/resources/elasticgroup/update.js#L18

I don't have experience with nodejs but looks like npm package `requestrertry` is just what we need.

**Comment by kmcgrath** [comment]
I have not run across this yet.  How long does the gateway timeout take to timeout?  And is "a couple seconds later" really 2 seconds?

I ask because there is a cap on how long the lambda function is able to run and I have not done a lot of testing with a function that exceeds the time limit.  (I have some testing scenarios in mind, randomizing a wait timer, etc...)

I want to see if I can duplicate this on my own before implementing.  I would like to see how long the Lambda function would need to run and what would happen with any timeouts associated with the lambda function itself.

The Lambda Service attempts to retry a failed function up to 3 times, so I think this should be fine.  What we don't want is a situation where the rest call goes through to Spotinst and then the lambda function dies before sending a request to CloudFormation, leaving you with a failed Stack but running ElasticGroup.

Right now, while it may not be ideal, the lambda function "does the right thing" and keeps both sides in sync. 

One possible solution may be to look at the execution time `context.getRemainingTimeInMillis()` before each retry and if there is less than 60(?) seconds left do not retry again.

**Comment by spa-87** [comment]
I didn't know about Lambda retries. In that case it should be enough I think.

Here're events from CloudFormation console: 
![cloudformation_events](https://cloud.githubusercontent.com/assets/6259448/16658492/3f0763a6-446f-11e6-934b-1b18a27a39d5.png)

And here're lambda logs. I've just found the second log stream with timeouts at the same time:
![cfn_lambda_logs1](https://cloud.githubusercontent.com/assets/6259448/16658584/8b48d344-446f-11e6-8f5a-4df7c4ec82fe.png)
![cfn_lambda_logs2](https://cloud.githubusercontent.com/assets/6259448/16658593/96824e98-446f-11e6-9912-4fa0332c36cc.png)

From these logs I can see 2 attempts to call lambda function with the same request id instead of 3 lambda retries. Is it correct?

**Comment by kmcgrath** [comment]
@spa-87 thank you for the logs.

The retries you see are not helping at this time. We actually closed a bug in cfn-responder which will stop the automatic retries on handled errors: https://github.com/SungardAS/cfn-responder/issues/1

The 504 is a handled error.  We capture it and can do something with it.  Right now that error is automatically forwarded to CloudFormation on the first invocation.  The retries are not helping, which was the bug fix in cfn-responder.

We need to figure out how long a handled 504 can continue to be retried before it could cause harm.  

For unhandled errors, like a Lambda Service timeout, the script will be fired again by AWS automatically.

Unhandled errors should die without notifying CloudFormation so that the Stack continues to wait for a response.

Handled errors should either immediately return a FAILED response to CloudFormation or perform their own retry until it is not safe to do so.  Like being too close to the function timing out.

**Comment by kmcgrath** [comment]
We have been doing a lot of work with AWS Lambda and retry attempts.  Working with the Spotinst team, it is our conclusion that we need to correlate reruns on with the Spotinst API and are moving down that path.  AWS Lambda has "run at least once" policy that complicates running any task more than once in a function.  I will be doing a bigger write up about the testing we did and the response we received from AWS support about Lambda and function invokes.
